security:
  basic:
    enabled: true
  user:
    name: sunxiaorong 
    password: xiaorong1111
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://sunxiaorong:xiaorong1111@localhost:8761/eureka
      