security:
  basic:
    enabled: true
  user:
    name: sunxiaorong 
    password: xiaorong1111
server:
  port: 8761
spring: 
  application: 
    name: material-discovery-eureka
eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sunxiaorong:xiaorong1111@localhost:8761/eureka
      